= Überblick am Beispiel Ilistal
:source-highlighter: rouge

== Aufbruchstimmung im Ilistal

=== Der Startschuss

Die Ferienregion Ilistal hat sich entschlossen, ihre Webpage auf Vordermann zu bringen. Das
vielfältige Transportangebot soll interaktiv mittels eines grafischen Dialogs abrufbar sein. Die
Präsentation im Gemeindehaus war beeindruckend: Schöne Bilder, trendige Abkürzungen
wie HTML, XML, GIS, SVG! Sogleich kamen natürlich weitere Wünsche auf. Im Bauamt
entschloss man sich kürzlich, die Adressen nach der neuen Norm zu erfassen. Das könnte
man doch nutzen! Der Direktor der Ilishornbahnen erinnert sich, dass der nationale
Bergbahnenverband einen Dienst einrichten möchte, über den das landesweite Bergbahn-
angebot verfügbar ist. Dabei sollen auch die Fahrpreise und insbesondere die verschiedenen
Verbundabonnemente abrufbar sein. Sein Kollege, der für die technischen Belange zustän-
dig ist, macht darauf aufmerksam, dass er auf seinem Compi die ganze Infrastruktur ver-
walte. Informationen über die Bahntrassees und die Pisten könne er schon liefern. Da sei
aber nicht alles klar. Kürzlich habe er nämlich auf dem Bauamt gefragt, ob er nicht die Daten
der neuen Überbauung «Im Oberboden» haben könne. Sie hätten es dann schliesslich hin-
gekriegt. Einige Informationen seien zwar verloren gegangen. Die seien aber nicht so wichtig
gewesen.
Da wird die Gemeindepräsidentin hellhörig. Eine Kollegin, die in einer Gemeinde nahe der

[,interlis]
----
INTERLIS 2.3;

/** !!------------------------------------------------------------------------------
 * !! Version    | wer | Änderung
 * !!------------------------------------------------------------------------------
 * !! 2025-01-15 | sz  | Ersterfassung
 * !!==============================================================================
 */
!!@ technicalContact=mailto:agi@bd.so.ch
!!@ furtherInformation=http://geo.so.ch/models/ARP/SO_ARP_SEin_Konfiguration_20250115.uml
!!@ title="SEin-App Konfiguration"
!!@ shortDescription="Datenmodell für die (Teil-)Konfiguration der SEin-App"
MODEL SO_ARP_SEin_Konfiguration_20250115 (de)
AT "https://arp.so.ch"
VERSION "2025-01-15"  =
  IMPORTS GeometryCHLV95_V1,Text;

  CLASS Gemeinde (ABSTRACT) =
    /** Name der Gemeinde (gemäss amtlichem Verzeichnis)
     */
    Name : MANDATORY TEXT*500;
    /** Offizielle Gemeindenummer
     */
    BFSNr : MANDATORY 2000 .. 3000;
    /** Geometrie
     */
    Geometrie : MANDATORY GeometryCHLV95_V1.MultiSurface;
    /** Name des Bezirks
     */
    Bezirk : MANDATORY TEXT*50;
    Handlungsraum : (
      urban,
      !!@ ili2db.dispName=ländlich
      laendlich,
      !!@ ili2db.dispName=agglomerationsgeprägt
      agglomerationsgepraegt
    );
  END Gemeinde;

  STRUCTURE Gruppe =
    /** Name der Themengruppe
     */
    Name : MANDATORY TEXT*500;
  END Gruppe;

  /** TODO: unique constraint Name und Gruppen-Name.
   */
  STRUCTURE Thema =
    /** Titel (Anzeigename) des Layers / der Layer.
     */
    Name : MANDATORY TEXT*500;
    /** Layer-ID (Name) des Layers gemäss Web GIS Client resp. GetCapabilities.
     */
    LayerId : TEXT*500;
    /** Transparenz in Prozent
     */
    LayerTransparenz : 0 .. 100;
  END Thema;

  /** Enthält Informationen zu einem (generischen) Objekt. Das sind ein Name / eine Beschreibung / eine Umbschreibung und ein Link z.B zu einem PDF oder eine Webseite.
   */
  STRUCTURE Objektinfo =
    /** Name / Beschreibung / Aussage zu dem Objekt.
     */
    Information : TEXT*1000;
    /** Link zum Objektblatt oder zu einer Webseite etc.
     */
    Link : URI;
  END Objektinfo;

  TOPIC Auswertung =

    STRUCTURE Thema
    EXTENDS SO_ARP_SEin_Konfiguration_20250115.Thema =
      /** Thema erweitert mit Objektinfos.
       */
      !!@ ili2db.mapping=JSON
      Objektinfos : BAG {0..*} OF SO_ARP_SEin_Konfiguration_20250115.Objektinfo;
      /** Ist Gemeinde von diesem Thema betroffen?
       */
      ist_betroffen : BOOLEAN;
    END Thema;

    STRUCTURE Gruppe
    EXTENDS SO_ARP_SEin_Konfiguration_20250115.Gruppe =
      /** Gruppe erweitert mit Themenliste.
       */
      !!@ ili2db.mapping=JSON
      Themen : BAG {1..*} OF SO_ARP_SEin_Konfiguration_20250115.Auswertung.Thema;
    END Gruppe;

    CLASS Gemeinde
    EXTENDS SO_ARP_SEin_Konfiguration_20250115.Gemeinde =
      /** Ausdehnung / Bounding Box
       */
      BoundingBox : MANDATORY TEXT*200;
      /** Liste sämtlicher Themen-Gruppen.
       */
      !!@ ili2db.mapping=JSON
      Gruppen : BAG {1..*} OF SO_ARP_SEin_Konfiguration_20250115.Auswertung.Gruppe;
      UNIQUE Name;
      UNIQUE BFSNr;
    END Gemeinde;

  END Auswertung;

  /** Achtung: Das funktioniert solange es immer eine Objektinfo gibt.
   * Dann weiss man, dass die Gemeinde von diesem Thema betroffen ist.
   * Scheint gemässt Liste jetzt so zu sein ("keine Geodaten").
   * Sonst bräuchte es noch eine Assoziation zw. Thema und Gemeinde
   * und zusätzlichen Umbaulogik von Grundlagen zu Auswertung.
   */
  TOPIC Grundlagen =

    CLASS Gemeinde
    EXTENDS SO_ARP_SEin_Konfiguration_20250115.Gemeinde =
      UNIQUE Name;
      UNIQUE BFSNr;
    END Gemeinde;

    CLASS Gruppe
    EXTENDS SO_ARP_SEin_Konfiguration_20250115.Gruppe =
    END Gruppe;

    /** Herkunft des Attributs
     */
    CLASS Objektinfo
    EXTENDS SO_ARP_SEin_Konfiguration_20250115.Objektinfo =
    END Objektinfo;

    CLASS Thema
    EXTENDS SO_ARP_SEin_Konfiguration_20250115.Thema =
    END Thema;

    ASSOCIATION Gemeinde_Objektinfo =
      Objektinfo_R -- {0..*} Objektinfo;
      Gemeinde_R -- {0..*} Gemeinde;
    END Gemeinde_Objektinfo;

    ASSOCIATION Gruppe_Thema =
      Thema_R -- {0..*} Thema;
      Gruppe_R -- {1} Gruppe;
    END Gruppe_Thema;

    ASSOCIATION Thema_Objektinfo =
      Objektinfo_R -- {0..*} Objektinfo;
      Thema_R -- {1} Thema;
    END Thema_Objektinfo;

  END Grundlagen;

END SO_ARP_SEin_Konfiguration_20250115.
----