:noindex:
=== Einleitung
In diesem Kapitel wird der sequentielle INTERLIS-Transferdienst beschrieben. Damit können Datenbestände zwischen verschiedenen Systemen systemneutral ausgetauscht werden. Der INTERLIS-Transferdienst unterstützt den vollständigen wie auch den inkrementellen (bzw. differenziellen) Austausch von Datenbeständen (Replikation). Der Transferdienst kann auf jedes INTERLIS-Modell angewendet werden. Damit ist es z.B. möglich Daten (Datenmodell) und Signaturobjekte (Signaturenmodell) mit dem gleichen Mechanismus zu transferieren.

Im Moment ist der INTERLIS-Transferdienst als Austausch von XML-Dateien definiert (www.w3.org/XML/). Zur breiteren Nutzung dieser INTERLIS-XML-Dateien ist es unter anderem auch möglich, XML-Schema-Dokumente (www.w3.org/XML/Schema) zu erzeugen. In Zukunft ist es jedoch denkbar, dass weitere INTERLIS-Transferdienste definiert werden (z.B. auf Basis Webservices oder CORBA). Aus diesem Grund ist die Beschreibung des INTERLIS-Transferdienstes in die Unterabschnitte _Allgemeine Regeln_ und _XML-Codierung_ unterteilt. Die allgemeinen Regeln gelten für _jeden sequentiellen_ INTERLIS-Transferdienst, unabhängig von der konkreten Codierung oder Übermittlung. Die Regeln unter _XML-Codierung_ gelten speziell für XML-formatierte INTERLIS-Transferdateien.
